cert:
  dnsName: "*.home.justinricheson.com"

# Creates ingresses for uis that are not running in the cluster
uis:
  - name: nas
    ingress:
      dnsName: nas.home.justinricheson.com
    service:
      host: nas-internal.home.justinricheson.com
      port: 8000