persistence:
  enabled: true
  storageClassName: "longhorn"
  size: 1Gi

admin:
  existingSecret: "grafana-secrets"
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://influxdb-influxdb2.influxdb.svc.cluster.local:80
        jsonData:
          version: Flux
          organization: home
          defaultBucket: home
          httpMode: POST
        secureJsonData:
          token: $INFLUX_TOKEN
        isDefault: true

envValueFrom:
  INFLUX_TOKEN:
    secretKeyRef:
      name: influxdb-influxdb2-auth
      key: admin-token

grafana.ini:
  dashboards:
    default_home_dashboard_path: /var/lib/grafana/dashboards/default/rclone-status.json

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    rclone-status:
      json: |
        {
          "title": "Rclone Status",
          "schemaVersion": 36,
          "version": 10,
          "time": {
            "from": "now-7d",
            "to": "now"
          },
          "panels": [
            {
              "id": 1,
              "title": "Daily Status",
              "type": "state-timeline",
              "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
              "datasource": { "type": "influxdb", "uid": "InfluxDB" },
              "targets": [
                {
                  "query": "from(bucket: \"home\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"status\")\n  |> drop(columns: [\"host\", \"topic\"])\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: true, timeSrc: \"_start\")",
                  "refId": "A"
                }
              ],
              "fieldConfig": {
                "defaults": {
                  "custom": {
                    "spanNulls": false
                  },
                  "color": {
                    "mode": "fixed",
                    "fixedColor": "blue"
                  },
                  "displayName": "Rclone Backup",
                  "mappings": [
                    { "type": "value", "options": { "success": { "color": "green" } } },
                    { "type": "value", "options": { "failure": { "color": "red" } } }
                  ]
                },
                "overrides": []
              }
            }
          ]
        }