config:
  agent:
    debug: true
  inputs:
    - mqtt_consumer:
        servers:
          - "tcp://mosquitto.mosquitto.svc.cluster.local:1883"
        topics:
          - "nas/rclone/status"
        data_format: "json"
        json_string_fields:
          - "status"
          - "time"
  outputs:
    - influxdb_v2:
        urls:
          - "http://influxdb-influxdb2.influxdb.svc.cluster.local:80"
        token: "$INFLUX_TOKEN"
        organization: "home"
        bucket: "home"
envFromSecret: "telegraf-secrets"
metrics:
  health:
    enabled: true