---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app.name }}-auth-secret
  namespace: {{ .Release.Namespace }}
data:
  users: {{ .Values.secret.hashedUsers | b64enc | quote }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cifs-secret
  namespace: {{ .Release.Namespace }}
data:
  CIFS_USERNAME: {{ .Values.secret.hashedCifsUser | quote }}
  CIFS_PASSWORD: {{ .Values.secret.hashedCifsPassword | quote }}