{{- $sans := dict }}
{{- range .Values.uis }}
{{- $parts := splitList "." .ingress.dnsName }}
{{- $wildcard := printf "*.%s" (join "." (rest $parts)) }}
{{- $_ := set $sans $wildcard true }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: wildcard-tls
  commonName: "{{ (keys $sans) | first }}"
  dnsNames:
    {{- range keys $sans }}
    - "{{ . }}"
    {{- end }}
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always