{{- range .Values.uis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .service.port }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    kubernetes.io/service-name: {{ .name }}
addressType: IPv4
ports:
  - name: http
    port: {{ .service.port }}
    protocol: TCP
endpoints:
  - addresses:
      - {{ .service.host | quote }}
{{- end }}