---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: wildcard-tls
  commonName: "{{ .Values.cert.dnsName }}"
  dnsNames:
    - "{{ .Values.cert.dnsName }}"
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always