---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: wildcard-tls
  commonName: '*.home.justinricheson.com'
  dnsNames:
    - '*.home.justinricheson.com'
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always