---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: technitium-dns
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  rules:
  - host: dns.home.justinricheson.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: technitium-dns
            port:
              number: 5380
  tls:
  - hosts:
    - dns.home.justinricheson.com
    secretName: wildcard-tls