# externalTrafficPolicy: Local is used so that the ip is only advertised from node(s) where the pod is running.
# Without this, MetalLB will arp advertise the ip on all nodes, and internally proxy requests when they land on a node where the pod isn't running.
# However, doing this means that the requests are internally NAT'ed, causing the source ip's to be replaced with an internal k8s ip.
# This causes technitium to show all requests coming from a single internal ip.

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: {{ .Values.app.name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.ip }}
  externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
  - name: http
    protocol: TCP
    port: 5380
    targetPort: 5380