app:
  name: zigbee2mqtt

cert:
  dnsName: "*.home.justinricheson.com"

ingress:
  dnsName: zigbee.home.justinricheson.com

deployment:
  image:
    repository: koenkk/zigbee2mqtt
    tag: latest

  mqtt:
    server: mqtt://mosquitto.mosquitto.svc.cluster.local:1883

volumes:
  size: 1Gi

secret:
  # Generate with: htpasswd -nbB admin "$ADMIN_PASSWORD"
  hashedUsers: "put the result in secrets.yaml"