---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    log_dest stdout