---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
    mqtt:
      server: {{ .Values.deployment.mqtt.server }}
    serial:
      port: /dev/zigbee
      adapter: zstack
    frontend:
      enabled: true
    permit_join: false