---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}

    spec:
      nodeSelector:
        role: zigbee

      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080

        env:
        - name: TZ
          value: America/Chicago
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: mqtt://mosquitto.mosquitto.svc.cluster.local:1883
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
          value: /dev/zigbee
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
          value: zstack
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
          value: "false"
        - name: ZIGBEE2MQTT_CONFIG_AVAILABILITY_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
          value: "true"

        volumeMounts:
        - name: zigbee
          mountPath: /dev/zigbee
        - name: udev
          mountPath: /run/udev
          readOnly: true
        - name: data
          mountPath: /app/data

      volumes:
      - name: zigbee
        hostPath:
          path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_12b171a97415f011bf02e374b887153e-if00-port0
          type: CharDevice
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.app.name }}-pvc