{{- range .Values.uis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .service.host }}
    ports:
      - port: {{ .service.port }}
{{- end }}