{{- range .Values.uis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .service.host }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
{{- end }}