ingress:
  enabled: true
  className: traefik
  hosts:
    - host: ha.home.justinricheson.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildcard-tls
      hosts:
        - ha.home.justinricheson.com

persistence:
  enabled: true
  existingClaim: home-assistant-pvc

configuration:
  enabled: true
  forceInit: false
  trusted_proxies:
    - 10.244.0.0/16