clusterIssuer:
  email: admin@home.justinricheson.com
  server: https://acme-v02.api.letsencrypt.org/directory
  #server: https://acme-staging-v02.api.letsencrypt.org/directory

secret:
  # Get from password vault
  apiToken: "put the result in secrets.yaml"