---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-api
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
  - name: http
    protocol: TCP
    port: 1984
    targetPort: 1984