---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: letsencrypt-wildcard-account-key
    solvers:
    - dns01:
        route53:
          region: {{ .Values.clusterIssuer.region }}
          accessKeyID: {{ .Values.clusterIssuer.accessKeyId }}
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key