---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: letsencrypt-wildcard-account-key
    solvers:
    - dns01:
        cloudflare:
          email: unused@example.com # Required but ignored when using token
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token