---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: route53-credentials-secret
  namespace: {{ .Release.Namespace }}
data:
  access-key-id: {{ .Values.secret.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.secret.secretAccessKey | b64enc | quote }}