apiVersion: v1
kind: Namespace
metadata:
  name: scrypted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrypted
  namespace: scrypted
  labels:
    app: scrypted
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: scrypted
  template:
    metadata:
      labels:
        app: scrypted
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: scrypted
        image: koush/scrypted:latest
        ports:
        - containerPort: 11080
        - containerPort: 37458
        - containerPort: 38469
        - containerPort: 37299
        - containerPort: 43869
        - containerPort: 5353
        volumeMounts:
        - name: storage
          mountPath: /server/volume
          readOnly: false
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: scrypted
spec:
  volumeName: storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
  namespace: scrypted
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/scrypted-storage