apiVersion: v1
kind: Namespace
metadata:
  name: technitium-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium-dns
  namespace: technitium-dns
  labels:
    app: technitium-dns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: technitium-dns
  template:
    metadata:
      labels:
        app: technitium-dns
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi1
      hostNetwork: true
      containers:
      - name: technitium-dns
        image: technitium/dns-server:latest
        ports:
        - containerPort: 53
        - containerPort: 5380
        volumeMounts:
        - name: config
          mountPath: /etc/dns
          readOnly: false
        - name: config-override
          mountPath: /etc/dns/dns.config
          subPath: dns.config
          readOnly: false
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: config-override
        configMap:
          name: config-override
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: technitium-dns
spec:
  volumeName: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  namespace: technitium-dns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/technitium-dns-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-override
  namespace: technitium-dns
binaryData:
  dns.config: RFMpBBUAAMPQAAABAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWC1SZWFsLUlQA3BpMQIBAAAAADUAAgAAAAAAAAAAAAAAAAAAAAA1AAEBAAAAACABAgAAAAAAAAAAAAAAAAAAAACAEA4AAAAALAEAACwBAAAAAAEA0AQBABg4AABwFwAAWAIAAAUAAAAYAAAAOAAAAADQBwAAECcAABAnAABg6gAAZAAAAGQAAABkAAAAAAAAAAAaAgAAGgIAAFAAAABVAwAAuwEAAFUDAAAAAAAJWC1SZWFsLUlQAAIAAAECAAAA3AUAAAIAAAAQAAAAAQGA9AMAHgAAAB4AAAAIBwAAECcAAAAAAAAKAAAAgDoJACwBAAAKAAAAAgAAAAkAAAAFAAAAHgAAAAEBAAEeAAAAAAFAaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL1N0ZXZlbkJsYWNrL2hvc3RzL21hc3Rlci9ob3N0cxgAAACpQnFJlgEAAAACAwIgY2xvdWRmbGFyZS1kbnMuY29tICgxLjEuMS4xOjg1MykDAiBjbG91ZGZsYXJlLWRucy5jb20gKDEuMC4wLjE6ODUzKQEDAAAA0AcAAAIAAAAAAABtAQAA