# Settings > General > Backup Settings
#   Select: Dns Settings
# Settings > General > Restore Settings

---
apiVersion: v1
kind: Namespace
metadata:
  name: technitium-dns

---
apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
  namespace: technitium-dns
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: technitium-dns
  type: LoadBalancer
  loadBalancerIP: 192.168.0.10
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: http
    protocol: TCP
    port: 5380
    targetPort: 5380

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium-dns
  namespace: technitium-dns
  labels:
    app: technitium-dns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: technitium-dns
  template:
    metadata:
      labels:
        app: technitium-dns
    spec:
      containers:
      - name: technitium-dns
        image: technitium/dns-server:latest
        ports:
        - containerPort: 53
        - containerPort: 5380
        volumeMounts:
        - name: config
          mountPath: /etc/dns
          readOnly: false
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: technitium-dns
spec:
  volumeName: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  namespace: technitium-dns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/technitium-dns-config